apiVersion: v1
kind: Deployment
metadata:
  name: guestbook
  labels:
    app: book
spec:
  replicas: 2
  selector:
    matchLabels:
       app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
      - name: nginx
        image: nginx
       
